/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chattingapp;

import java.awt.Button;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.TextField;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ABC
 */
public class ServerJFrame extends javax.swing.JFrame {
    JPanel p1;
    /**
     * Creates new form ServerJFrame
     */
    public ServerJFrame() {
        p1=new JPanel();
        p1.setLayout(null);
        p1.setBackground(Color.BLUE);
        p1.setBounds(0,0,450,70);
        add(p1);
        
        ImageIcon icon1=new ImageIcon(ClassLoader.getSystemResource("chattingapp/photo/icon2.png"));
        Image icon2=icon1.getImage().getScaledInstance(30, 30, Image.SCALE_DEFAULT);
        ImageIcon icon3=new ImageIcon(icon2);
        JLabel la1=new JLabel(icon3);
        la1.setBounds(5, 20, 30, 30);
        p1.add(la1);
        
        ImageIcon icon4=new ImageIcon(ClassLoader.getSystemResource("chattingapp/photo/user.png"));
        Image icon5=icon4.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT);
        ImageIcon icon6=new ImageIcon(icon5);
        JLabel la2=new JLabel(icon6);
        la2.setBounds(40, 5, 60, 60);
        p1.add(la2);
        
        ImageIcon iconPhone=new ImageIcon(ClassLoader.getSystemResource("chattingapp/photo/phone.png"));
        Image iconPhone1=iconPhone.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT);
        ImageIcon iconPhone2=new ImageIcon(iconPhone1);
        JLabel laPhone=new JLabel(iconPhone2);
        laPhone.setBounds(350, 5, 60, 60);
        p1.add(laPhone);
        
        ImageIcon iconVideo=new ImageIcon(ClassLoader.getSystemResource("chattingapp/photo/videoCall.png"));
        Image iconVideo1=iconVideo.getImage().getScaledInstance(40, 40, Image.SCALE_DEFAULT);
        ImageIcon iconVideo2=new ImageIcon(iconVideo1);
        JLabel laVideo=new JLabel(iconVideo2);
        laVideo.setBounds(290, 5, 60, 60);
        p1.add(laVideo);
        
        TextField t1=new TextField();
        t1.setBounds(5, 500, 310, 40);
        t1.setFont(new Font("SAN_SERIF",Font.PLAIN,16));
        add(t1);
        
        ImageIcon iconSend=new ImageIcon(ClassLoader.getSystemResource("chattingapp/photo/msg.png"));
        Image iconSend1=iconSend.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT);
        ImageIcon iconSend2=new ImageIcon(iconSend1);
        //JLabel laSend=new JLabel(iconSend2);
        //laSend.setBounds(360, 500, 50, 50);
        //add(laSend);
        JButton btnSend;
        btnSend = new JButton(iconSend2);
        btnSend.setBounds(360, 500, 50, 50);
        add(btnSend);
        
        JTextArea area=new JTextArea();
        area.setBounds(5, 80, 430, 400);
        area.setBackground(Color.white);
        add(area);
        
        getContentPane().setBackground(Color.lightGray);
        setLayout(null);
        setSize(450, 600);
        setLocation(400, 200);
        setVisible(true);
        //initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
